<?php

namespace Database\Seeders;

use App\Models\Branch;
use App\Models\District;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class BranchSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $branches = [
            [
                'district_id' => District::where('name', 'Muzaffarabad')->first()->id,
                'region_id' => District::where('name', 'Muzaffarabad')->first()->region_id,
                'code' => '0001',
                'name' => 'Main Branch Muzaffarabad',
                'address' => 'Fatima Plaza, Chatter Domel Muzaffarabad',
            ],
            [
                'district_id' => District::where('name', 'Mirpur')->first()->id,
                'region_id' => District::where('name', 'Mirpur')->first()->region_id,
                'code' => '0002',
                'name' => 'Main Branch Mirpur',
                'address' => 'Nishat Centre, Allama Iqbal Road, Mirpur',
            ],
            [
                'district_id' => District::where('name', 'Mirpur')->first()->id,
                'region_id' => District::where('name', 'Mirpur')->first()->region_id,
                'code' => '0003',
                'name' => 'Dadyal Branch',
                'address' => 'Maqbool Butt Shaheed Chowk, Dadyal',
            ],
            [
                'district_id' => District::where('name', 'Mirpur')->first()->id,
                'region_id' => District::where('name', 'Mirpur')->first()->region_id,
                'code' => '0004',
                'name' => 'Chaksawari Branch',
                'address' => 'Opposite Al-Shahzad Hotel Chaksawari',
            ],
            [
                'district_id' => District::where('name', 'Kotli')->first()->id,
                'region_id' => District::where('name', 'Kotli')->first()->region_id,
                'code' => '0005',
                'name' => 'Kotli Branch',
                'address' => 'Poonch / Rawalpindi Road Kotli',
            ],
            [
                'district_id' => District::where('name', 'Poonch')->first()->id,
                'region_id' => District::where('name', 'Poonch')->first()->region_id,
                'code' => '0006',
                'name' => 'Rawalakot Branch',
                'address' => 'Gulf Shopping Complex Katchari Road Rawalakot',
            ],
            [
                'district_id' => District::where('name', 'Kotli')->first()->id,
                'region_id' => District::where('name', 'Kotli')->first()->region_id,
                'code' => '0007',
                'name' => 'Sehnsa Branch',
                'address' => 'Main Bazar Sehnsa AJK',
            ],
            [
                'district_id' => District::where('name', 'Neelum')->first()->id,
                'region_id' => District::where('name', 'Neelum')->first()->region_id,
                'code' => '0008',
                'name' => 'Athmuqam Branch',
                'address' => 'Main Bazar Athmuqam District Neelum AJK',
            ],
            [
                'district_id' => District::where('name', 'Mirpur')->first()->id,
                'region_id' => District::where('name', 'Mirpur')->first()->region_id,
                'code' => '0009',
                'name' => 'Islamgarh Branch',
                'address' => 'Main Bazar Islamgarh District Mirpur AJK',
            ],
            [
                'district_id' => District::where('name', 'Bagh')->first()->id,
                'region_id' => District::where('name', 'Bagh')->first()->region_id,
                'code' => '0010',
                'name' => 'Bagh Branch',
                'address' => 'Main Bazar Bagh AJK',
            ],
            [
                'district_id' => District::where('name', 'Bagh')->first()->id,
                'region_id' => District::where('name', 'Bagh')->first()->region_id,
                'code' => '0011',
                'name' => 'Arja Branch',
                'address' => 'Bagh/Rawalakot Chowk Arja District Bagh AJK',
            ],
            [
                'district_id' => District::where('name', 'Bhimber')->first()->id,
                'region_id' => District::where('name', 'Bhimber')->first()->region_id,
                'code' => '0012',
                'name' => 'Bhimber Branch',
                'address' => 'Main Bazar Bhimber AJK',
            ],
            [
                'district_id' => District::where('name', 'Poonch')->first()->id,
                'region_id' => District::where('name', 'Poonch')->first()->region_id,
                'code' => '0013',
                'name' => 'Pallandari Branch',
                'address' => 'Main Bazar Pallandari AJK',
            ],
            [
                'district_id' => District::where('name', 'Kotli')->first()->id,
                'region_id' => District::where('name', 'Kotli')->first()->region_id,
                'code' => '0014',
                'name' => 'Nar Branch',
                'address' => 'Main Bazar Nar District Kotli AJK',
            ],
            [
                'district_id' => District::where('name', 'Mirpur')->first()->id,
                'region_id' => District::where('name', 'Mirpur')->first()->region_id,
                'code' => '0015',
                'name' => 'F-3 Branch, Mirpur',
                'address' => 'Sector F-3 Mirpur AJK',
            ],
            [
                'district_id' => District::where('name', 'Poonch')->first()->id,
                'region_id' => District::where('name', 'Poonch')->first()->region_id,
                'code' => '0016',
                'name' => 'Hajeera Branch',
                'address' => 'Main Bazar Hajeera District Poonch Azad Kashmir',
            ],
            [
                'district_id' => District::where('name', 'Muzaffarabad')->first()->id,
                'region_id' => District::where('name', 'Muzaffarabad')->first()->region_id,
                'code' => '0017',
                'name' => 'Garhi-Dupata Branch',
                'address' => 'Pull Bazar Garhi Dupatta Muzaffarabad A.K',
            ],
            [
                'district_id' => District::where('name', 'Muzaffarabad')->first()->id,
                'region_id' => District::where('name', 'Muzaffarabad')->first()->region_id,
                'code' => '0018',
                'name' => 'Lower Plate Branch',
                'address' => 'Near City Hospital Lower Plate Muzaffarabad A.K',
            ],
            [
                'district_id' => District::where('name', 'Muzaffarabad')->first()->id,
                'region_id' => District::where('name', 'Muzaffarabad')->first()->region_id,
                'code' => '0019',
                'name' => 'Chatter Klass Branch',
                'address' => 'Kullian Bazar, Kohala-Muzaffarabad Road',
            ],
            [
                'district_id' => District::where('name', 'Kotli')->first()->id,
                'region_id' => District::where('name', 'Kotli')->first()->region_id,
                'code' => '0020',
                'name' => 'Brahtla Branch',
                'address' => 'Main Bazar Brahtla District Kotli A.K',
            ],
            [
                'district_id' => District::where('name', 'Kotli')->first()->id,
                'region_id' => District::where('name', 'Kotli')->first()->region_id,
                'code' => '0021',
                'name' => 'Khui Ratta Branch',
                'address' => 'Main Bazar Khui Ratta District Kotli A.K',
            ],
            [
                'district_id' => District::where('name', 'Muzaffarabad')->first()->id,
                'region_id' => District::where('name', 'Muzaffarabad')->first()->region_id,
                'code' => '0022',
                'name' => 'Chakaar Branch',
                'address' => 'Main Bazar Chakaar District Muzaffarabad A.K',
            ],
            [
                'district_id' => District::where('name', 'Bagh')->first()->id,
                'region_id' => District::where('name', 'Bagh')->first()->region_id,
                'code' => '0023',
                'name' => 'Dheerkot Branch',
                'address' => 'Main Bazar Dheerkot District Bagh A.K',
            ],
            [
                'district_id' => District::where('name', 'Muzaffarabad')->first()->id,
                'region_id' => District::where('name', 'Muzaffarabad')->first()->region_id,
                'code' => '0024',
                'name' => 'Pathika Branch',
                'address' => 'Main Bazar Pathika District Muzaffarabad A.K',
            ],
            [
                'district_id' => District::where('name', 'Poonch')->first()->id,
                'region_id' => District::where('name', 'Poonch')->first()->region_id,
                'code' => '0025',
                'name' => 'Bandi Abbaspur Branch',
                'address' => 'Pul Bazar Bandi Abbaspur District Poonch A.K',
            ],
            [
                'district_id' => District::where('name', 'Kotli')->first()->id,
                'region_id' => District::where('name', 'Kotli')->first()->region_id,
                'code' => '0026',
                'name' => 'Sarsawa Branch',
                'address' => 'Main Bazar Sarsawa District Kotli A.K',
            ],
            [
                'district_id' => District::where('name', 'Mirpur')->first()->id,
                'region_id' => District::where('name', 'Mirpur')->first()->region_id,
                'code' => '0027',
                'name' => 'Pulmanda Branch',
                'address' => 'Main Bazar Pulmanda District Mirpur A.K',
            ],
            [
                'district_id' => District::where('name', 'Muzaffarabad')->first()->id,
                'region_id' => District::where('name', 'Muzaffarabad')->first()->region_id,
                'code' => '0028',
                'name' => 'Madina Market Branch',
                'address' => 'Madina Market District Muzaffarabad A.K',
            ],
            [
                'district_id' => District::where('name', 'Bhimber')->first()->id,
                'region_id' => District::where('name', 'Bhimber')->first()->region_id,
                'code' => '0029',
                'name' => 'Barnala Branch',
                'address' => 'Main Bazar Barnala District Bhimber A.K',
            ],
            [
                'district_id' => District::where('name', 'Poonch')->first()->id,
                'region_id' => District::where('name', 'Poonch')->first()->region_id,
                'code' => '0030',
                'name' => 'Khai-gala Branch',
                'address' => 'Main Bazar Khai-gala District Poonch A.K',
            ],
            [
                'district_id' => District::where('name', 'Kotli')->first()->id,
                'region_id' => District::where('name', 'Kotli')->first()->region_id,
                'code' => '0031',
                'name' => 'Khad-Gujran Branch',
                'address' => 'Main Bazar Khad-Gujran District Kotli A.K',
            ],
            [
                'district_id' => District::where('name', 'Sudhanoti')->first()->id,
                'region_id' => District::where('name', 'Sudhanoti')->first()->region_id,
                'code' => '0032',
                'name' => 'Trarkhal Branch',
                'address' => 'Main Bazar Tararkhal District Sudhanoti',
            ],
            [
                'district_id' => District::where('name', 'Bhimber')->first()->id,
                'region_id' => District::where('name', 'Bhimber')->first()->region_id,
                'code' => '0033',
                'name' => 'Chowki Branch',
                'address' => 'Main Bazar Chowki District Bhimber A.K',
            ],
            [
                'district_id' => District::where('name', 'Jhelum Valley')->first()->id,
                'region_id' => District::where('name', 'Jhelum Valley')->first()->region_id,
                'code' => '0034',
                'name' => 'Hattian Branch',
                'address' => 'Sakhi Plaza, Chowk Bazar, Hattian Bala',
            ],
            [
                'district_id' => District::where('name', 'Bhimber')->first()->id,
                'region_id' => District::where('name', 'Bhimber')->first()->region_id,
                'code' => '0035',
                'name' => 'Poona Branch',
                'address' => 'Main Bazar Poona District Bhimber A.K',
            ],
            [
                'district_id' => District::where('name', 'Kotli')->first()->id,
                'region_id' => District::where('name', 'Kotli')->first()->region_id,
                'code' => '0036',
                'name' => 'Charhoi Branch',
                'address' => 'Main Bazar Charhoi District Kotli A.K',
            ],
            [
                'district_id' => District::where('name', 'Jhelum Valley')->first()->id,
                'region_id' => District::where('name', 'Jhelum Valley')->first()->region_id,
                'code' => '0037',
                'name' => 'Chakothi Branch',
                'address' => 'Main Bazar Chakhoti District Hattian A.K',
            ],
            [
                'district_id' => District::where('name', 'Haveli')->first()->id,
                'region_id' => District::where('name', 'Haveli')->first()->region_id,
                'code' => '0038',
                'name' => 'Kahotta Branch',
                'address' => 'Main Bazar Kahotta District Haveli A.K',
            ],
            [
                'district_id' => District::where('name', 'Poonch')->first()->id,
                'region_id' => District::where('name', 'Poonch')->first()->region_id,
                'code' => '0039',
                'name' => 'Paniola Branch',
                'address' => 'Main Bazar Paniola District Poonch A.K',
            ],
            [
                'district_id' => District::where('name', 'Muzaffarabad')->first()->id,
                'region_id' => District::where('name', 'Muzaffarabad')->first()->region_id,
                'code' => '0040',
                'name' => 'District Complex Muzaffarabad Branch',
                'address' => 'Old Secretariat District Complex District Muzaffarabd',
            ],
            [
                'district_id' => District::where('name', 'Sudhanoti')->first()->id,
                'region_id' => District::where('name', 'Sudhanoti')->first()->region_id,
                'code' => '0041',
                'name' => 'Bloch Branch',
                'address' => 'Main Bazar Bloch District Sudhanoti',
            ],
            [
                'district_id' => District::where('name', 'Kotli')->first()->id,
                'region_id' => District::where('name', 'Kotli')->first()->region_id,
                'code' => '0042',
                'name' => 'Tatta-Pani Branch',
                'address' => 'Main Bazar Tatta-Pani District Kotli A.K',
            ],
            [
                'district_id' => District::where('name', 'Neelum')->first()->id,
                'region_id' => District::where('name', 'Neelum')->first()->region_id,
                'code' => '0043',
                'name' => 'Sharda Branch',
                'address' => 'Main Sharda Bazar District Neelum A.K',
            ],
            [
                'district_id' => District::where('name', 'Kotli')->first()->id,
                'region_id' => District::where('name', 'Kotli')->first()->region_id,
                'code' => '0044',
                'name' => 'Mi-Toti Branch',
                'address' => 'Main Bazar Mi-Toti District Kotli A.K',
            ],
            [
                'district_id' => District::where('name', 'Mirpur')->first()->id,
                'region_id' => District::where('name', 'Mirpur')->first()->region_id,
                'code' => '0045',
                'name' => 'Jatlan Branch',
                'address' => 'Main Bazar Jatlan District Mirpur',
            ],
            [
                'district_id' => District::where('name', 'Mirpur')->first()->id,
                'region_id' => District::where('name', 'Mirpur')->first()->region_id,
                'code' => '0046',
                'name' => 'Mian Muhammad Town Branch',
                'address' => 'Mian Muhammad Town District Mirpur A.K',
            ],
            [
                'district_id' => District::where('name', 'Mirpur')->first()->id,
                'region_id' => District::where('name', 'Mirpur')->first()->region_id,
                'code' => '0047',
                'name' => 'Jhatti Dheri Branch',
                'address' => 'Jhatti Dheri Cross District Mirpur A.K',
            ],
            [
                'district_id' => District::where('name', 'Kotli')->first()->id,
                'region_id' => District::where('name', 'Kotli')->first()->region_id,
                'code' => '0048',
                'name' => 'Dhanna Branch',
                'address' => 'Dhanna Bazar District Kotli A.K',
            ],
            [
                'district_id' => District::where('name', 'Sudhanoti')->first()->id,
                'region_id' => District::where('name', 'Sudhanoti')->first()->region_id,
                'code' => '0049',
                'name' => 'Talian Branch',
                'address' => 'Main Bazar Talian District Sadhnutti A.K',
            ],
            [
                'district_id' => District::where('name', 'Poonch')->first()->id,
                'region_id' => District::where('name', 'Poonch')->first()->region_id,
                'code' => '0050',
                'name' => 'Thorar Branch',
                'address' => 'Main Bazar Thorar District Poonch A.K',
            ],
            [
                'district_id' => District::where('name', 'Kotli')->first()->id,
                'region_id' => District::where('name', 'Kotli')->first()->region_id,
                'code' => '0051',
                'name' => 'Juna Branch',
                'address' => 'Main Bazar Juna District Kotli A.K',
            ],
            [
                'district_id' => District::where('name', 'Neelum')->first()->id,
                'region_id' => District::where('name', 'Neelum')->first()->region_id,
                'code' => '0052',
                'name' => 'Joora Branch',
                'address' => 'Main Bazar Joora District Neelum A.K',
            ],
            [
                'district_id' => District::where('name', 'Muzaffarabad')->first()->id,
                'region_id' => District::where('name', 'Muzaffarabad')->first()->region_id,
                'code' => '0053',
                'name' => 'Ladies Branch, Muzaffarabad',
                'address' => 'Hashim Plaza, Poultry Farm Road, Muzaffarabad, AK',
            ],
            [
                'district_id' => District::where('name', 'Mirpur')->first()->id,
                'region_id' => District::where('name', 'Mirpur')->first()->region_id,
                'code' => '0054',
                'name' => 'Ladies Branch, Mirpur',
                'address' => 'Haris Plaza Chowk Shaheedan Sector C-2 Mirpur AK',
            ],
            [
                'district_id' => District::where('name', 'Kotli')->first()->id,
                'region_id' => District::where('name', 'Kotli')->first()->region_id,
                'code' => '0055',
                'name' => 'Seharmandi Branch',
                'address' => 'Main Bazar Seharmandi, Tehsil Sehensa District Kotli AK',
            ],
            [
                'district_id' => District::where('name', 'Poonch')->first()->id,
                'region_id' => District::where('name', 'Poonch')->first()->region_id,
                'code' => '0056',
                'name' => 'CMH Road Rawalakot Branch',
                'address' => 'CMH Road Rawalakot AK',
            ],
            [
                'district_id' => District::where('name', 'Mirpur')->first()->id,
                'region_id' => District::where('name', 'Mirpur')->first()->region_id,
                'code' => '0057',
                'name' => 'Main Bazar Chakswari Branch',
                'address' => 'Main Bazar Chakswari Tehsil & District Mirpur AK',
            ],
            [
                'district_id' => District::where('name', 'Mirpur')->first()->id,
                'region_id' => District::where('name', 'Mirpur')->first()->region_id,
                'code' => '0058',
                'name' => 'Ratta Branch Mirpur',
                'address' => 'Allah Abad Market Main Road Ratta Tehsil Dadyal Distt. Mirpur',
            ],
            [
                'district_id' => District::where('name', 'Bhimber')->first()->id,
                'region_id' => District::where('name', 'Bhimber')->first()->region_id,
                'code' => '0059',
                'name' => 'Moil Branch',
                'address' => 'Tehsil & District Bhimber AK',
            ],
            [
                'district_id' => District::where('name', 'Poonch')->first()->id,
                'region_id' => District::where('name', 'Poonch')->first()->region_id,
                'code' => '0060',
                'name' => 'Banbehk Branch',
                'address' => 'Tehsil & District Poonch',
            ],
            [
                'district_id' => District::where('name', 'Muzaffarabad')->first()->id,
                'region_id' => District::where('name', 'Muzaffarabad')->first()->region_id,
                'code' => '0061',
                'name' => 'Upper Ada Branch',
                'address' => 'Near Shah Anayat Darbar Upper Ada Muzaffarabad',
            ],
            [
                'district_id' => District::where('name', 'Jhelum Valley')->first()->id,
                'region_id' => District::where('name', 'Jhelum Valley')->first()->region_id,
                'code' => '0062',
                'name' => 'Chathian Branch',
                'address' => 'Srinagar Road, Chathian Bazar, Dist. Hattian Bala',
            ],
            [
                'district_id' => District::where('name', 'Neelum')->first()->id,
                'region_id' => District::where('name', 'Neelum')->first()->region_id,
                'code' => '0063',
                'name' => 'Kutton Branch',
                'address' => 'Kutton, Tehsil Authmuqam, District Neelum',
            ],
            [
                'district_id' => District::where('name', 'Kotli')->first()->id,
                'region_id' => District::where('name', 'Kotli')->first()->region_id,
                'code' => '0064',
                'name' => 'Jarahi Branch',
                'address' => 'Tehsil Dolya Jattan, District Kotli',
            ],
            [
                'district_id' => District::where('name', 'Kotli')->first()->id,
                'region_id' => District::where('name', 'Kotli')->first()->region_id,
                'code' => '0065',
                'name' => 'Goi Branch',
                'address' => 'Village & P.O Goi Tehsil & District Kotli',
            ],
            [
                'district_id' => District::where('name', 'Kotli')->first()->id,
                'region_id' => District::where('name', 'Kotli')->first()->region_id,
                'code' => '0066',
                'name' => 'Lorry Adda Branch',
                'address' => 'Lorry Adda, Tehsil & District Kotli, AJK',
            ],
            [
                'district_id' => District::where('name', 'Muzaffarabad')->first()->id,
                'region_id' => District::where('name', 'Muzaffarabad')->first()->region_id,
                'code' => '0067',
                'name' => 'Gojra By-Pass Branch',
                'address' => 'Gojra By-Pass Road, Near WAPDA Colony, Muzaffarabad AJK',
            ],
            [
                'district_id' => District::where('name', 'Sudhanoti')->first()->id,
                'region_id' => District::where('name', 'Sudhanoti')->first()->region_id,
                'code' => '0068',
                'name' => 'Mang Branch',
                'address' => 'Mang Bazar, Near AC Office, District Sudhnuti AJK',
            ],
            [
                'district_id' => District::where('name', 'Neelum')->first()->id,
                'region_id' => District::where('name', 'Neelum')->first()->region_id,
                'code' => '0069',
                'name' => 'Kundal Shahi Branch',
                'address' => 'Main Bazar, Kundal Shahi, Tehsil Athmuqam, District Neelum',
            ],
            [
                'district_id' => District::where('name', 'Muzaffarabad')->first()->id,
                'region_id' => District::where('name', 'Muzaffarabad')->first()->region_id,
                'code' => '0070',
                'name' => 'Brarkot Branch',
                'address' => 'Abbottabad Road Brarkot Tehsil & District Muzaffarabad A.K',
            ],
            [
                'district_id' => District::where('name', 'Sudhanoti')->first()->id,
                'region_id' => District::where('name', 'Sudhanoti')->first()->region_id,
                'code' => '0071',
                'name' => 'Muslimabad Branch',
                'address' => 'Pattan Sher Khan, Tehsil Mang, District Sudhunoti, Azad Kashmir',
            ],
            [
                'district_id' => District::where('name', 'Sudhanoti')->first()->id,
                'region_id' => District::where('name', 'Sudhanoti')->first()->region_id,
                'code' => '0072',
                'name' => 'Islam Nagar Branch',
                'address' => 'Pattan Sher Khan, Tehsil Mang, District Sudhunoti, Azad Kashmir',
            ],
            [
                'district_id' => District::where('name', 'Bhimber')->first()->id,
                'region_id' => District::where('name', 'Bhimber')->first()->region_id,
                'code' => '0073',
                'name' => 'Samahni Branch',
                'address' => 'Shahrah-e-Jammu, Samahni, District Bhimber, Azad Kashmir',
            ],
            [
                'district_id' => District::where('name', 'Sudhanoti')->first()->id,
                'region_id' => District::where('name', 'Sudhanoti')->first()->region_id,
                'code' => '0074',
                'name' => 'Panthal Branch',
                'address' => 'Panthal Branch, Tehsil and District Sudhanoti, Azad Kashmir',
            ],
            [
                'district_id' => District::where('name', 'Kotli')->first()->id,
                'region_id' => District::where('name', 'Kotli')->first()->region_id,
                'code' => '0075',
                'name' => 'Nakyal Branch',
                'address' => 'Nakyal, Fatehpur Thakyala, District Kotli, Azad Kashmir',
            ],
            [
                'district_id' => District::where('name', 'Jhelum Valley')->first()->id,
                'region_id' => District::where('name', 'Jhelum Valley')->first()->region_id,
                'code' => '0076',
                'name' => 'Chinari Branch',
                'address' => 'Main Bazar Chinari, Azad Kashmir',
            ],
            [
                'district_id' => District::where('name', 'Muzaffarabad')->first()->id,
                'region_id' => District::where('name', 'Muzaffarabad')->first()->region_id,
                'code' => '0077',
                'name' => 'PM House Road Branch',
                'address' => 'Near PM House Muzaffarabad, Azad Kashmir',
            ],
            [
                'district_id' => District::where('name', 'Bhimber')->first()->id,
                'region_id' => District::where('name', 'Bhimber')->first()->region_id,
                'code' => '0078',
                'name' => 'Kot Jamel Branch',
                'address' => 'Kot Jamel Tehsil Barnala Distt. Bhimber, Azad Kashmir',
            ],
            [
                'district_id' => District::where('name', 'Mirpur')->first()->id,
                'region_id' => District::where('name', 'Mirpur')->first()->region_id,
                'code' => '0079',
                'name' => 'Kotli Road Branch Mirpur',
                'address' => 'Kotli Road branch opposite PWD Office Mirpur, Azad Kashmir',
            ],
            [
                'district_id' => District::where('name', 'Mirpur')->first()->id,
                'region_id' => District::where('name', 'Mirpur')->first()->region_id,
                'code' => '0080',
                'name' => 'Mangla Hamlet',
                'address' => 'Main Bazar, Mangla Hamlet, Tehsil and District, Mirpur, Azad Kashmir',
            ],
            [
                'district_id' => District::where('name', 'Mirpur')->first()->id,
                'region_id' => District::where('name', 'Mirpur')->first()->region_id,
                'code' => '0081',
                'name' => 'Khanabad',
                'address' => 'Khanabad Tehsil and District Mirpur, Azad Kashmir',
            ],
            [
                'district_id' => District::where('name', 'Kotli')->first()->id,
                'region_id' => District::where('name', 'Kotli')->first()->region_id,
                'code' => '0082',
                'name' => 'Bypass Road Branch',
                'address' => 'Gulhar Shareef Chowk, Kotli, Azad Kashmir',
            ],
            [
                'district_id' => District::where('name', 'Poonch')->first()->id,
                'region_id' => District::where('name', 'Poonch')->first()->region_id,
                'code' => '0083',
                'name' => 'Public Housing Scheme Branch',
                'address' => 'Bank Road Rawalakot (AK)',
            ],
            [
                'district_id' => District::where('name', 'Jhelum Valley')->first()->id,
                'region_id' => District::where('name', 'Jhelum Valley')->first()->region_id,
                'code' => '0084',
                'name' => 'Main Bazar Leepa',
                'address' => 'Jhelum Valley (AJ&K)',
            ],
            [
                'district_id' => District::where('name', 'Muzaffarabad')->first()->id,
                'region_id' => District::where('name', 'Muzaffarabad')->first()->region_id,
                'code' => '0085',
                'name' => 'Chella Bandi Branch',
                'address' => 'Neelum Road, Chella Bandi, Muzaffarabad AJK',
            ],
        ];


        foreach ($branches as $branch) {
            Branch::create($branch);
        }

    }
}
