<?php

namespace Database\Seeders;

use App\Models\Checklist;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ChecklistSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $loan_sub_category = [
            ['loan_sub_category_id' => 1, 'sequence_no' => 1, 'route' => 'applicant.edit', 'name' => 'Basic Applicant Information', 'status' => 'active'],
            ['loan_sub_category_id' => 1, 'sequence_no' => 2, 'route' => 'applicant.employment-information.edit', 'name' => 'Employment Information', 'status' => 'active'],
            ['loan_sub_category_id' => 1, 'sequence_no' => 3, 'route' => 'applicant.requested-loan-information.edit', 'name' => 'Requested Loan Information', 'status' => 'active'],
            ['loan_sub_category_id' => 1, 'sequence_no' => 4, 'route' => 'guarantor.index', 'name' => 'Guarantor', 'status' => 'active'],
            ['loan_sub_category_id' => 1, 'sequence_no' => 5, 'route' => 'finance_facility.index', 'name' => 'Existing Finance Facility', 'status' => 'active'],
            ['loan_sub_category_id' => 1, 'sequence_no' => 6, 'route' => 'security.index', 'name' => 'Security Information', 'status' => 'active'],
            ['loan_sub_category_id' => 1, 'sequence_no' => 7, 'route' => 'reference.index', 'name' => 'Reference (AT LEAST TWO)', 'status' => 'active'],
            ['loan_sub_category_id' => 1, 'sequence_no' => 8, 'route' => 'document.index', 'name' => 'Document List (Attachments)', 'status' => 'active'],
            ['loan_sub_category_id' => 1, 'sequence_no' => 9, 'route' => 'list-house-hold-item.index', 'name' => 'List of House Hold Items with duly attested verified by the branch', 'status' => 'active'],
            ['loan_sub_category_id' => 1, 'sequence_no' => 10, 'route' => 'obligor-score-card.index', 'name' => 'Obligor Score Card', 'status' => 'active'],
            ['loan_sub_category_id' => 1, 'sequence_no' => 11, 'route' => 'fact-sheet.index', 'name' => "Basic Borrower's Fact Sheet", 'status' => 'active'],
            ['loan_sub_category_id' => 1, 'sequence_no' => 12, 'route' => 'pnws.index', 'name' => "Personal Net Worth Statement", 'status' => 'active'],
            ['loan_sub_category_id' => 1, 'sequence_no' => 13, 'route' => 'guarantor-undertaking-credit-report.index', 'name' => 'Guarantor’s Credit Report/ Under taking', 'status' => 'active'],
            ['loan_sub_category_id' => 1, 'sequence_no' => 14, 'route' => 'employer.undertaking', 'name' => 'Employer Undertaking', 'status' => 'active'],


//            ['loan_sub_category_id' => 1, 'sequence_no' => 6, 'name' => 'E-CIB or Affidavit in lieu of ECIB & Data Check Report', 'status' => 'active'],
//            ['loan_sub_category_id' => 1, 'sequence_no' => 8, 'name' => 'List of House Hold Items with duly attested verified by the branch', 'status' => 'active'],
//            ['loan_sub_category_id' => 1, 'sequence_no' => 9, 'name' => 'Certificate Regarding Non-Availment Of Credit Facility From Other Banks', 'status' => 'active'],
//            ['loan_sub_category_id' => 1, 'sequence_no' => 10, 'name' => 'Statement of Account of the applicant showing one month salary credit', 'status' => 'active'],
//            ['loan_sub_category_id' => 1, 'sequence_no' => 11, 'name' => 'Obligor Score Card', 'status' => 'active'],
//            ['loan_sub_category_id' => 1, 'sequence_no' => 12, 'name' => 'Attested photocopy of CNIC of applicant', 'status' => 'active'],
//            ['loan_sub_category_id' => 1, 'sequence_no' => 13, 'name' => 'Attested photocopies of salary slips of the applicant', 'status' => 'active'],
//            ['loan_sub_category_id' => 1, 'sequence_no' => 14, 'name' => 'Attested photocopy of salary slip of guarantor', 'status' => 'active'],
//            ['loan_sub_category_id' => 1, 'sequence_no' => 15, 'name' => 'Attested photocopy of CNIC of guarantor', 'status' => 'active'],

            ['loan_sub_category_id' => 2, 'sequence_no' => NULL, 'name' => NULL, 'status' => 'active'],
            ['loan_sub_category_id' => 2, 'sequence_no' => NULL, 'name' => NULL, 'status' => 'active'],
            ['loan_sub_category_id' => 2, 'sequence_no' => NULL, 'name' => NULL, 'status' => 'active'],
            ['loan_sub_category_id' => 2, 'sequence_no' => NULL, 'name' => NULL, 'status' => 'active'],
            ['loan_sub_category_id' => 2, 'sequence_no' => NULL, 'name' => NULL, 'status' => 'active'],
            ['loan_sub_category_id' => 2, 'sequence_no' => NULL, 'name' => NULL, 'status' => 'active'],
            ['loan_sub_category_id' => 2, 'sequence_no' => NULL, 'name' => NULL, 'status' => 'active'],
            ['loan_sub_category_id' => 2, 'sequence_no' => NULL, 'name' => NULL, 'status' => 'active'],
            ['loan_sub_category_id' => 2, 'sequence_no' => NULL, 'name' => NULL, 'status' => 'active'],
            ['loan_sub_category_id' => 2, 'sequence_no' => NULL, 'name' => NULL, 'status' => 'active'],
            ['loan_sub_category_id' => 3, 'sequence_no' => 1, 'name' => 'Application Form', 'status' => 'active'],
            ['loan_sub_category_id' => 3, 'sequence_no' => 2, 'name' => 'Borrower’s Basic Fact Sheet (BBFS)', 'status' => 'active'],
            ['loan_sub_category_id' => 3, 'sequence_no' => 3, 'name' => 'Personal Net worth Statement (PNWS)', 'status' => 'active'],
            ['loan_sub_category_id' => 3, 'sequence_no' => 4, 'name' => 'Employers Under taking', 'status' => 'active'],
            ['loan_sub_category_id' => 3, 'sequence_no' => 5, 'name' => 'Guarantor’s Credit Report/ Under taking', 'status' => 'active'],
            ['loan_sub_category_id' => 3, 'sequence_no' => 6, 'name' => 'Data Check & Affidavit in lieu of ECIB', 'status' => 'active'],
            ['loan_sub_category_id' => 3, 'sequence_no' => 7, 'name' => 'NOC by Branch Manager that the applicant has not availed loans from other Banks / FIs.', 'status' => 'active'],
            ['loan_sub_category_id' => 3, 'sequence_no' => 8, 'name' => 'Last Month Salary slip (for salaried Person)', 'status' => 'active'],
            ['loan_sub_category_id' => 3, 'sequence_no' => 9, 'name' => 'Attested copy of CNIC of Guarantor', 'status' => 'active'],
            ['loan_sub_category_id' => 3, 'sequence_no' => 10, 'name' => 'Six Month statement of Account with BAJK or any other Bank', 'status' => 'active'],
            ['loan_sub_category_id' => 3, 'sequence_no' => 11, 'name' => 'Account statement showing one month salary credit', 'status' => 'active'],
            ['loan_sub_category_id' => 3, 'sequence_no' => 12, 'name' => 'Two Passport size photograph', 'status' => 'active'],
            ['loan_sub_category_id' => 3, 'sequence_no' => 13, 'name' => 'Quotation from authorized dealer', 'status' => 'active'],
            ['loan_sub_category_id' => 3, 'sequence_no' => 14, 'name' => 'Statement of Account for last one year of Business Account', 'status' => 'active'],
            ['loan_sub_category_id' => 3, 'sequence_no' => 15, 'name' => 'Income Statement', 'status' => 'active'],
            ['loan_sub_category_id' => 3, 'sequence_no' => 16, 'name' => 'NTN certificate', 'status' => 'active'],
            ['loan_sub_category_id' => 3, 'sequence_no' => 17, 'name' => 'Last Month Paid Electricity / telephone Bill paid', 'status' => 'active'],
            ['loan_sub_category_id' => 3, 'sequence_no' => 18, 'name' => 'If not banking with us , certificate from bank regarding borrower standing financial means and history of honoring past obligations', 'status' => 'active'],
            ['loan_sub_category_id' => 4, 'sequence_no' => 1, 'name' => 'Client Request', 'status' => 'active'],
            ['loan_sub_category_id' => 4, 'sequence_no' => 2, 'name' => 'Loan Application Form (BAJK Approved Performa)', 'status' => 'active'],
            ['loan_sub_category_id' => 4, 'sequence_no' => 3, 'name' => 'Borrower’s Basic Fact Sheet (BBFS)', 'status' => 'active'],
            ['loan_sub_category_id' => 4, 'sequence_no' => 4, 'name' => 'Copy of CNIC (Dully verified by Branch)', 'status' => 'active'],
            ['loan_sub_category_id' => 4, 'sequence_no' => 5, 'name' => 'PNWS', 'status' => 'active'],
            ['loan_sub_category_id' => 4, 'sequence_no' => 6, 'name' => 'Copy of NTN (if available)', 'status' => 'active'],
            ['loan_sub_category_id' => 4, 'sequence_no' => 7, 'name' => 'Manager’s Certificate', 'status' => 'active'],
            ['loan_sub_category_id' => 4, 'sequence_no' => 8, 'name' => 'Data Check & Affidavit in Lieu of Ecib', 'status' => 'active'],
            ['loan_sub_category_id' => 4, 'sequence_no' => 9, 'name' => 'Collateral Visit Report of Branch', 'status' => 'active'],
            ['loan_sub_category_id' => 4, 'sequence_no' => 10, 'name' => 'Copies of Security Documents (Title, NEC, etc.)', 'status' => 'active'],
            ['loan_sub_category_id' => 4, 'sequence_no' => 11, 'name' => 'Pre/Post Mortgage Legal Opinion', 'status' => 'active'],
            ['loan_sub_category_id' => 4, 'sequence_no' => 12, 'name' => 'Valuation Reports of Valuator', 'status' => 'active'],
            ['loan_sub_category_id' => 4, 'sequence_no' => 13, 'name' => 'Statements of Account', 'status' => 'active'],
            ['loan_sub_category_id' => 5, 'sequence_no' => 1, 'name' => 'Application Form', 'status' => 'active'],
            ['loan_sub_category_id' => 5, 'sequence_no' => 2, 'name' => 'Borrower’s Basic Fact Sheet (BBFS)', 'status' => 'active'],
            ['loan_sub_category_id' => 5, 'sequence_no' => 3, 'name' => 'Personal Net worth Statement (PNWS)', 'status' => 'active'],
            ['loan_sub_category_id' => 5, 'sequence_no' => 4, 'name' => 'Employers Under taking', 'status' => 'active'],
            ['loan_sub_category_id' => 5, 'sequence_no' => 5, 'name' => 'Guarantor’s Credit Report/ Under taking', 'status' => 'active'],
            ['loan_sub_category_id' => 5, 'sequence_no' => 6, 'name' => 'Data Check & Affidavit in lieu of ECIB', 'status' => 'active'],
            ['loan_sub_category_id' => 5, 'sequence_no' => 7, 'name' => 'NOC by Branch Manager that the applicant has not availed loans from other Banks / FIs.', 'status' => 'active'],
            ['loan_sub_category_id' => 5, 'sequence_no' => 8, 'name' => 'Last Month Salary slip (for salaried Person)', 'status' => 'active'],
            ['loan_sub_category_id' => 5, 'sequence_no' => 9, 'name' => 'Attested copy of CNIC of Guarantor', 'status' => 'active'],
            ['loan_sub_category_id' => 5, 'sequence_no' => 10, 'name' => 'Six Month statement of Account with BAJK or any other Bank', 'status' => 'active'],
            ['loan_sub_category_id' => 5, 'sequence_no' => 11, 'name' => 'Account statement showing one month salary credit', 'status' => 'active'],
            ['loan_sub_category_id' => 5, 'sequence_no' => 12, 'name' => 'Two Passport size photograph', 'status' => 'active'],
            ['loan_sub_category_id' => 5, 'sequence_no' => 13, 'name' => 'Quotation from authorized dealer', 'status' => 'active'],
            ['loan_sub_category_id' => 5, 'sequence_no' => 14, 'name' => 'Statement of Account for last one year of Business Account', 'status' => 'active'],
            ['loan_sub_category_id' => 5, 'sequence_no' => 15, 'name' => 'Income Statement', 'status' => 'active'],
            ['loan_sub_category_id' => 5, 'sequence_no' => 16, 'name' => 'NTN certificate', 'status' => 'active'],
            ['loan_sub_category_id' => 5, 'sequence_no' => 17, 'name' => 'Last Month Paid Electricity / telephone Bill paid', 'status' => 'active'],
            ['loan_sub_category_id' => 5, 'sequence_no' => 18, 'name' => 'If not banking with us , certificate from bank regarding borrower standing financial means and history of honoring past obligations', 'status' => 'active'],
            ['loan_sub_category_id' => 6, 'sequence_no' => 1, 'name' => 'Loan Application Form', 'status' => 'active'],
            ['loan_sub_category_id' => 6, 'sequence_no' => 2, 'name' => 'Attested copy of CNIC of applicant', 'status' => 'active'],
            ['loan_sub_category_id' => 6, 'sequence_no' => 3, 'name' => 'Attested copy of latest Salary slip (for Salaried Person)', 'status' => 'active'],
            ['loan_sub_category_id' => 6, 'sequence_no' => 4, 'name' => 'Quotation from authorized dealers', 'status' => 'active'],
            ['loan_sub_category_id' => 6, 'sequence_no' => 5, 'name' => 'Statement of Account', 'status' => 'active'],
            ['loan_sub_category_id' => 6, 'sequence_no' => 6, 'name' => 'Departmental Under taking (for Salaried Person)', 'status' => 'active'],
            ['loan_sub_category_id' => 6, 'sequence_no' => 7, 'name' => 'Borrower’s Basic Fact Sheet (BBFS)', 'status' => 'active'],
            ['loan_sub_category_id' => 6, 'sequence_no' => 8, 'name' => 'Personal Net worth Statement (PNWS)', 'status' => 'active'],
            ['loan_sub_category_id' => 6, 'sequence_no' => 9, 'name' => 'Guarantor’s Credit Report/ Under taking', 'status' => 'active'],
            ['loan_sub_category_id' => 6, 'sequence_no' => 10, 'name' => 'Attested copy of CNIC of Guarantor', 'status' => 'active'],
            ['loan_sub_category_id' => 6, 'sequence_no' => 11, 'name' => 'Attested copy of latest Salary slip of Guarantor', 'status' => 'active'],
            ['loan_sub_category_id' => 6, 'sequence_no' => 12, 'name' => 'Data Check Affidavit in lieu of ECIB', 'status' => 'active'],
            ['loan_sub_category_id' => 6, 'sequence_no' => 13, 'name' => 'NOC by Branch Manager that the applicant has not availed loans from other Banks / FIs.', 'status' => 'active'],
            ['loan_sub_category_id' => 7, 'sequence_no' => 1, 'name' => 'Check List Personal Loan', 'status' => 'active'],
            ['loan_sub_category_id' => 7, 'sequence_no' => 2, 'name' => 'Application Form', 'status' => 'active'],
            ['loan_sub_category_id' => 7, 'sequence_no' => 3, 'name' => 'Borrower’s Basic Fact Sheet (BBFS)', 'status' => 'active'],
            ['loan_sub_category_id' => 7, 'sequence_no' => 4, 'name' => 'Personal Net worth Statement (PNWS)', 'status' => 'active'],
            ['loan_sub_category_id' => 7, 'sequence_no' => 5, 'name' => 'Statement of account/ photocopy of certificate / deposit slips', 'status' => 'active'],
            ['loan_sub_category_id' => 7, 'sequence_no' => 6, 'name' => 'Marking of Lien & encashment authority in case the loan is against the deposits of other banks / Govt securities', 'status' => 'active'],
            ['loan_sub_category_id' => 7, 'sequence_no' => 7, 'name' => 'Under taking of account / TDR holder for marking lien, with certification of the manger regarding marking of Lien.', 'status' => 'active'],
            ['loan_sub_category_id' => 7, 'sequence_no' => 8, 'name' => 'In case of Third party list of House Hold Items', 'status' => 'active'],
            ['loan_sub_category_id' => 7, 'sequence_no' => 9, 'name' => 'Attested Copy of CNIC of applicant.', 'status' => 'active'],
            ['loan_sub_category_id' => 8, 'sequence_no' => 1, 'name' => 'Client Request', 'status' => 'active'],
            ['loan_sub_category_id' => 8, 'sequence_no' => 2, 'name' => 'Loan Application Form (BAJK Approved Performa)', 'status' => 'active'],
            ['loan_sub_category_id' => 8, 'sequence_no' => 3, 'name' => 'Borrower’s Basic Fact Sheet (BBFS)', 'status' => 'active'],
            ['loan_sub_category_id' => 8, 'sequence_no' => 4, 'name' => 'Copy of CNIC (Dully verified by Branch)', 'status' => 'active'],
            ['loan_sub_category_id' => 8, 'sequence_no' => 5, 'name' => 'PNWS (Proprietor/Partners/Directors)', 'status' => 'active'],
            ['loan_sub_category_id' => 8, 'sequence_no' => 6, 'name' => 'Copy of NTN (if available)', 'status' => 'active'],
            ['loan_sub_category_id' => 8, 'sequence_no' => 7, 'name' => 'Manager’s Certificate', 'status' => 'active'],
            ['loan_sub_category_id' => 8, 'sequence_no' => 8, 'name' => 'Client’s Declaration regarding Loans from BAJK and other banks', 'status' => 'active'],
            ['loan_sub_category_id' => 8, 'sequence_no' => 9, 'name' => 'Client’s Declaration regarding Proprietorship', 'status' => 'active'],
            ['loan_sub_category_id' => 8, 'sequence_no' => 10, 'name' => 'Audited/ Financial Statements', 'status' => 'active'],
            ['loan_sub_category_id' => 8, 'sequence_no' => 11, 'name' => 'Business Visit Report of Branch', 'status' => 'active'],
            ['loan_sub_category_id' => 8, 'sequence_no' => 12, 'name' => 'Collateral Visit Report of Branch', 'status' => 'active'],
            ['loan_sub_category_id' => 8, 'sequence_no' => 13, 'name' => 'Copies of Security Documents (Title, NEC, etc.)', 'status' => 'active'],
            ['loan_sub_category_id' => 8, 'sequence_no' => 14, 'name' => 'Pre/Post Mortgage Legal Opinion', 'status' => 'active'],
            ['loan_sub_category_id' => 8, 'sequence_no' => 15, 'name' => 'Valuation Reports of Valuator', 'status' => 'active'],
            ['loan_sub_category_id' => 8, 'sequence_no' => 16, 'name' => 'Search Report (Pertains to Companies)', 'status' => 'active'],
            ['loan_sub_category_id' => 8, 'sequence_no' => 17, 'name' => 'Verified Stock Report', 'status' => 'active'],
            ['loan_sub_category_id' => 8, 'sequence_no' => 18, 'name' => 'Statements of CD, RF, DF, Accounts (BAJK & Other Banks)', 'status' => 'active'],
            ['loan_sub_category_id' => 8, 'sequence_no' => 19, 'name' => 'Partnership Deed / Form H (In Partnership Cases)', 'status' => 'active'],
            ['loan_sub_category_id' => 8, 'sequence_no' => 20, 'name' => 'Memorandum & Article of Association (Companies)', 'status' => 'active'],
            ['loan_sub_category_id' => 8, 'sequence_no' => 21, 'name' => 'Certificate of Incorporation (Firm/Company)', 'status' => 'active'],
            ['loan_sub_category_id' => 8, 'sequence_no' => 22, 'name' => 'Certificate of Commencement of Business (Company)', 'status' => 'active'],
            ['loan_sub_category_id' => 8, 'sequence_no' => 23, 'name' => 'Form – 29 (Latest) (Company)', 'status' => 'active'],
            ['loan_sub_category_id' => 8, 'sequence_no' => 24, 'name' => 'Board Resolution (In case of Pvt Ltd Co', 'status' => 'active'],
            ['loan_sub_category_id' => 9, 'sequence_no' => 1, 'name' => 'Client Request', 'status' => 'active'],
            ['loan_sub_category_id' => 9, 'sequence_no' => 2, 'name' => 'Loan Application Form (BAJK Approved Performa)', 'status' => 'active'],
            ['loan_sub_category_id' => 9, 'sequence_no' => 3, 'name' => 'Borrower’s Basic Fact Sheet (BBFS)', 'status' => 'active'],
            ['loan_sub_category_id' => 9, 'sequence_no' => 4, 'name' => 'Copy of CNIC (Dully verified by Branch)', 'status' => 'active'],
            ['loan_sub_category_id' => 9, 'sequence_no' => 5, 'name' => 'PNWS (Proprietor/Partners/Directors)', 'status' => 'active'],
            ['loan_sub_category_id' => 9, 'sequence_no' => 6, 'name' => 'Copy of NTN (if available)', 'status' => 'active'],
            ['loan_sub_category_id' => 9, 'sequence_no' => 7, 'name' => 'Manager’s Certificate', 'status' => 'active'],
            ['loan_sub_category_id' => 9, 'sequence_no' => 8, 'name' => 'Client’s Declaration regarding Loans from BAJK and other Banks', 'status' => 'active'],
            ['loan_sub_category_id' => 9, 'sequence_no' => 9, 'name' => 'Client’s Declaration regarding Proprietorship', 'status' => 'active'],
            ['loan_sub_category_id' => 9, 'sequence_no' => 10, 'name' => 'Audited/ Financial Statements', 'status' => 'active'],
            ['loan_sub_category_id' => 9, 'sequence_no' => 11, 'name' => 'Business Visit Report of Branch', 'status' => 'active'],
            ['loan_sub_category_id' => 9, 'sequence_no' => 12, 'name' => 'Collateral Visit Report of Branch', 'status' => 'active'],
            ['loan_sub_category_id' => 9, 'sequence_no' => 13, 'name' => 'Copies of Security Documents (Title, NEC, etc.)', 'status' => 'active'],
            ['loan_sub_category_id' => 9, 'sequence_no' => 14, 'name' => 'Pre/Post Mortgage Legal Opinion', 'status' => 'active'],
            ['loan_sub_category_id' => 9, 'sequence_no' => 15, 'name' => 'Valuation Reports of Valuator', 'status' => 'active'],
            ['loan_sub_category_id' => 9, 'sequence_no' => 16, 'name' => 'Search Report (Pertains to Companies)', 'status' => 'active'],
            ['loan_sub_category_id' => 9, 'sequence_no' => 17, 'name' => 'Verified Stock Report', 'status' => 'active'],
            ['loan_sub_category_id' => 9, 'sequence_no' => 18, 'name' => 'Statements of CD, RF, DF, Accounts (BAJK & Other Banks)', 'status' => 'active'],
            ['loan_sub_category_id' => 9, 'sequence_no' => 19, 'name' => 'Partnership Deed / Form H (In Partnership Cases)', 'status' => 'active'],
            ['loan_sub_category_id' => 9, 'sequence_no' => 20, 'name' => 'Memorandum & Article of Association (Companies)', 'status' => 'active'],
            ['loan_sub_category_id' => 9, 'sequence_no' => 21, 'name' => 'Certificate of Incorporation (Firm/Company)', 'status' => 'active'],
            ['loan_sub_category_id' => 9, 'sequence_no' => 22, 'name' => 'Certificate of Commencement of Business (Company)', 'status' => 'active'],
            ['loan_sub_category_id' => 9, 'sequence_no' => 23, 'name' => 'Form – 29 (Latest) (Company)', 'status' => 'active'],
            ['loan_sub_category_id' => 9, 'sequence_no' => 24, 'name' => 'Board Resolution (In case of Pvt Ltd Co', 'status' => 'active'],
            ['loan_sub_category_id' => 10, 'sequence_no' => 1, 'name' => 'Client Request', 'status' => 'active'],
            ['loan_sub_category_id' => 10, 'sequence_no' => 2, 'name' => 'Loan Application Form (BAJK Approved Performa)', 'status' => 'active'],
            ['loan_sub_category_id' => 10, 'sequence_no' => 3, 'name' => 'Borrower’s Basic Fact Sheet (BBFS)', 'status' => 'active'],
            ['loan_sub_category_id' => 10, 'sequence_no' => 4, 'name' => 'Copy of CNIC (Dully verified by Branch)', 'status' => 'active'],
            ['loan_sub_category_id' => 10, 'sequence_no' => 5, 'name' => 'PNWS (Proprietor/Partners/Directors)', 'status' => 'active'],
            ['loan_sub_category_id' => 10, 'sequence_no' => 6, 'name' => 'Copy of NTN (if available)', 'status' => 'active'],
            ['loan_sub_category_id' => 10, 'sequence_no' => 7, 'name' => 'Manager’s Certificate', 'status' => 'active'],
            ['loan_sub_category_id' => 10, 'sequence_no' => 8, 'name' => 'Client’s Declaration regarding Loans from BAJK and other Banks', 'status' => 'active'],
            ['loan_sub_category_id' => 10, 'sequence_no' => 9, 'name' => 'Client’s Declaration regarding Proprietorship', 'status' => 'active'],
            ['loan_sub_category_id' => 10, 'sequence_no' => 10, 'name' => 'Audited/ Financial Statements', 'status' => 'active'],
            ['loan_sub_category_id' => 10, 'sequence_no' => 11, 'name' => 'Business Visit Report of Branch', 'status' => 'active'],
            ['loan_sub_category_id' => 10, 'sequence_no' => 12, 'name' => 'Collateral Visit Report of Branch', 'status' => 'active'],
            ['loan_sub_category_id' => 10, 'sequence_no' => 13, 'name' => 'Copies of Security Documents (Title, NEC, etc.)', 'status' => 'active'],
            ['loan_sub_category_id' => 10, 'sequence_no' => 14, 'name' => 'Pre/Post Mortgage Legal Opinion', 'status' => 'active'],
            ['loan_sub_category_id' => 10, 'sequence_no' => 15, 'name' => 'Valuation Reports of Valuator', 'status' => 'active'],
            ['loan_sub_category_id' => 10, 'sequence_no' => 16, 'name' => 'Search Report (Pertains to Companies)', 'status' => 'active'],
            ['loan_sub_category_id' => 10, 'sequence_no' => 17, 'name' => 'Verified Stock Report', 'status' => 'active'],
            ['loan_sub_category_id' => 10, 'sequence_no' => 18, 'name' => 'Statements of CD, RF, DF, Accounts (BAJK & Other Banks)', 'status' => 'active'],
            ['loan_sub_category_id' => 10, 'sequence_no' => 19, 'name' => 'Partnership Deed / Form H (In Partnership Cases)', 'status' => 'active'],
            ['loan_sub_category_id' => 10, 'sequence_no' => 20, 'name' => 'Memorandum & Article of Association (Companies)', 'status' => 'active'],
            ['loan_sub_category_id' => 10, 'sequence_no' => 21, 'name' => 'Certificate of Incorporation (Firm/Company)', 'status' => 'active'],
            ['loan_sub_category_id' => 10, 'sequence_no' => 22, 'name' => 'Certificate of Commencement of Business (Company)', 'status' => 'active'],
            ['loan_sub_category_id' => 10, 'sequence_no' => 23, 'name' => 'Form – 29 (Latest) (Company)', 'status' => 'active'],
            ['loan_sub_category_id' => 10, 'sequence_no' => 24, 'name' => 'Board Resolution (In case of Pvt Ltd Co', 'status' => 'active'],
            ['loan_sub_category_id' => 11, 'sequence_no' => 1, 'name' => 'Client Request', 'status' => 'active'],
            ['loan_sub_category_id' => 11, 'sequence_no' => 2, 'name' => 'Loan Application Form (BAJK Approved Performa)', 'status' => 'active'],
            ['loan_sub_category_id' => 11, 'sequence_no' => 3, 'name' => 'Borrower’s Basic Fact Sheet (BBFS)', 'status' => 'active'],
            ['loan_sub_category_id' => 11, 'sequence_no' => 4, 'name' => 'Copy of CNIC (Dully verified by Branch)', 'status' => 'active'],
            ['loan_sub_category_id' => 11, 'sequence_no' => 5, 'name' => 'PNWS (Proprietor/Partners/Directors)', 'status' => 'active'],
            ['loan_sub_category_id' => 11, 'sequence_no' => 6, 'name' => 'Copy of NTN (if available)', 'status' => 'active'],
            ['loan_sub_category_id' => 11, 'sequence_no' => 7, 'name' => 'Manager’s Certificate', 'status' => 'active'],
            ['loan_sub_category_id' => 11, 'sequence_no' => 8, 'name' => 'Client’s Declaration regarding Loans from BAJK and other Banks', 'status' => 'active'],
            ['loan_sub_category_id' => 11, 'sequence_no' => 9, 'name' => 'Client’s Declaration regarding Proprietorship', 'status' => 'active'],
            ['loan_sub_category_id' => 11, 'sequence_no' => 10, 'name' => 'Audited/ Financial Statements', 'status' => 'active'],
            ['loan_sub_category_id' => 11, 'sequence_no' => 11, 'name' => 'Business Visit Report of Branch', 'status' => 'active'],
            ['loan_sub_category_id' => 11, 'sequence_no' => 12, 'name' => 'Collateral Visit Report of Branch', 'status' => 'active'],
            ['loan_sub_category_id' => 11, 'sequence_no' => 13, 'name' => 'Copies of Security Documents (Title, NEC, etc.)', 'status' => 'active'],
            ['loan_sub_category_id' => 11, 'sequence_no' => 14, 'name' => 'Pre/Post Mortgage Legal Opinion', 'status' => 'active'],
            ['loan_sub_category_id' => 11, 'sequence_no' => 15, 'name' => 'Valuation Reports of Valuator', 'status' => 'active'],
            ['loan_sub_category_id' => 11, 'sequence_no' => 16, 'name' => 'Search Report (Pertains to Companies)', 'status' => 'active'],
            ['loan_sub_category_id' => 11, 'sequence_no' => 17, 'name' => 'Verified Stock Report', 'status' => 'active'],
            ['loan_sub_category_id' => 11, 'sequence_no' => 18, 'name' => 'Statements of CD, RF, DF, Accounts (BAJK & Other Banks)', 'status' => 'active'],
            ['loan_sub_category_id' => 11, 'sequence_no' => 19, 'name' => 'Partnership Deed / Form H (In Partnership Cases)', 'status' => 'active'],
            ['loan_sub_category_id' => 11, 'sequence_no' => 20, 'name' => 'Memorandum & Article of Association (Companies)', 'status' => 'active'],
            ['loan_sub_category_id' => 11, 'sequence_no' => 21, 'name' => 'Certificate of Incorporation (Firm/Company)', 'status' => 'active'],
            ['loan_sub_category_id' => 11, 'sequence_no' => 22, 'name' => 'Certificate of Commencement of Business (Company)', 'status' => 'active'],
            ['loan_sub_category_id' => 11, 'sequence_no' => 23, 'name' => 'Form – 29 (Latest) (Company)', 'status' => 'active'],
            ['loan_sub_category_id' => 11, 'sequence_no' => 24, 'name' => 'Board Resolution (In case of Pvt Ltd Co', 'status' => 'active'],
            ['loan_sub_category_id' => 12, 'sequence_no' => NULL, 'name' => NULL, 'status' => 'active'],
            ['loan_sub_category_id' => 12, 'sequence_no' => NULL, 'name' => NULL, 'status' => 'active'],
            ['loan_sub_category_id' => 12, 'sequence_no' => NULL, 'name' => NULL, 'status' => 'active'],
            ['loan_sub_category_id' => 12, 'sequence_no' => NULL, 'name' => NULL, 'status' => 'active'],
            ['loan_sub_category_id' => 12, 'sequence_no' => NULL, 'name' => NULL, 'status' => 'active'],
            ['loan_sub_category_id' => 12, 'sequence_no' => NULL, 'name' => NULL, 'status' => 'active'],
            ['loan_sub_category_id' => 12, 'sequence_no' => NULL, 'name' => NULL, 'status' => 'active'],
            ['loan_sub_category_id' => 12, 'sequence_no' => NULL, 'name' => NULL, 'status' => 'active'],
            ['loan_sub_category_id' => 12, 'sequence_no' => NULL, 'name' => NULL, 'status' => 'active'],
            ['loan_sub_category_id' => 12, 'sequence_no' => NULL, 'name' => NULL, 'status' => 'active'],
            ['loan_sub_category_id' => 13, 'sequence_no' => NULL, 'name' => NULL, 'status' => 'active'],
            ['loan_sub_category_id' => 13, 'sequence_no' => NULL, 'name' => NULL, 'status' => 'active'],
            ['loan_sub_category_id' => 13, 'sequence_no' => NULL, 'name' => NULL, 'status' => 'active'],
            ['loan_sub_category_id' => 13, 'sequence_no' => NULL, 'name' => NULL, 'status' => 'active'],
            ['loan_sub_category_id' => 13, 'sequence_no' => NULL, 'name' => NULL, 'status' => 'active'],
            ['loan_sub_category_id' => 13, 'sequence_no' => NULL, 'name' => NULL, 'status' => 'active'],
            ['loan_sub_category_id' => 13, 'sequence_no' => NULL, 'name' => NULL, 'status' => 'active'],
            ['loan_sub_category_id' => 13, 'sequence_no' => NULL, 'name' => NULL, 'status' => 'active'],
            ['loan_sub_category_id' => 13, 'sequence_no' => NULL, 'name' => NULL, 'status' => 'active'],
            ['loan_sub_category_id' => 13, 'sequence_no' => NULL, 'name' => NULL, 'status' => 'active'],
            ['loan_sub_category_id' => 14, 'sequence_no' => NULL, 'name' => NULL, 'status' => 'active'],
            ['loan_sub_category_id' => 14, 'sequence_no' => NULL, 'name' => NULL, 'status' => 'active'],
            ['loan_sub_category_id' => 14, 'sequence_no' => NULL, 'name' => NULL, 'status' => 'active'],
            ['loan_sub_category_id' => 14, 'sequence_no' => NULL, 'name' => NULL, 'status' => 'active'],
            ['loan_sub_category_id' => 14, 'sequence_no' => NULL, 'name' => NULL, 'status' => 'active'],
            ['loan_sub_category_id' => 14, 'sequence_no' => NULL, 'name' => NULL, 'status' => 'active'],
            ['loan_sub_category_id' => 14, 'sequence_no' => NULL, 'name' => NULL, 'status' => 'active'],
            ['loan_sub_category_id' => 14, 'sequence_no' => NULL, 'name' => NULL, 'status' => 'active'],
            ['loan_sub_category_id' => 14, 'sequence_no' => NULL, 'name' => NULL, 'status' => 'active'],
            ['loan_sub_category_id' => 14, 'sequence_no' => NULL, 'name' => NULL, 'status' => 'active'],
            ['loan_sub_category_id' => 15, 'sequence_no' => 1, 'name' => 'Client Request', 'status' => 'active'],
            ['loan_sub_category_id' => 15, 'sequence_no' => 2, 'name' => 'Loan Application Form (BAJK Approved Performa)', 'status' => 'active'],
            ['loan_sub_category_id' => 15, 'sequence_no' => 3, 'name' => 'Borrower’s Basic Fact Sheet (BBFS)', 'status' => 'active'],
            ['loan_sub_category_id' => 15, 'sequence_no' => 4, 'name' => 'Copy of CNIC (Dully verified by Branch)', 'status' => 'active'],
            ['loan_sub_category_id' => 15, 'sequence_no' => 5, 'name' => 'PNWS (', 'status' => 'active'],
            ['loan_sub_category_id' => 15, 'sequence_no' => 6, 'name' => 'Copy of NTN (if available)', 'status' => 'active'],
            ['loan_sub_category_id' => 15, 'sequence_no' => 7, 'name' => 'Manager’s Certificate', 'status' => 'active'],
            ['loan_sub_category_id' => 15, 'sequence_no' => 8, 'name' => 'Client’s Declaration regarding Loans from BAJK and other Banks', 'status' => 'active'],
            ['loan_sub_category_id' => 15, 'sequence_no' => 9, 'name' => 'Client’s Declaration regarding Proprietorship', 'status' => 'active'],
            ['loan_sub_category_id' => 15, 'sequence_no' => 10, 'name' => 'Business Visit Report of Branch', 'status' => 'active'],
            ['loan_sub_category_id' => 15, 'sequence_no' => 11, 'name' => 'Collateral Visit Report of Branch', 'status' => 'active'],
            ['loan_sub_category_id' => 15, 'sequence_no' => 12, 'name' => 'Copies of Security Documents (Title, NEC, etc.)', 'status' => 'active'],
            ['loan_sub_category_id' => 15, 'sequence_no' => 13, 'name' => 'Pre/Post Mortgage Legal Opinion', 'status' => 'active'],
            ['loan_sub_category_id' => 15, 'sequence_no' => 14, 'name' => 'Valuation Reports of Valuator', 'status' => 'active'],
            ['loan_sub_category_id' => 15, 'sequence_no' => 15, 'name' => 'Verified Stock Report', 'status' => 'active'],
            ['loan_sub_category_id' => 15, 'sequence_no' => 16, 'name' => 'Statements of Accounts', 'status' => 'active'],
            ['loan_sub_category_id' => 16, 'sequence_no' => 1, 'name' => 'Application Form', 'status' => 'active'],
            ['loan_sub_category_id' => 16, 'sequence_no' => 2, 'name' => 'Borrower’s Basic Fact Sheet (BBFS)', 'status' => 'active'],
            ['loan_sub_category_id' => 16, 'sequence_no' => 3, 'name' => 'Personal Net worth Statement (PNWS)', 'status' => 'active'],
            ['loan_sub_category_id' => 16, 'sequence_no' => 4, 'name' => 'Physical Verification by BM', 'status' => 'active'],
            ['loan_sub_category_id' => 16, 'sequence_no' => 5, 'name' => 'Guarantor’s Credit Report/ Under taking', 'status' => 'active'],
            ['loan_sub_category_id' => 16, 'sequence_no' => 6, 'name' => 'E-CIB or Affidavit in lieu of ECIB Data Check Report', 'status' => 'active'],
            ['loan_sub_category_id' => 16, 'sequence_no' => 7, 'name' => 'Stock Report', 'status' => 'active'],
            ['loan_sub_category_id' => 16, 'sequence_no' => 8, 'name' => 'Statement of Accounts', 'status' => 'active'],
            ['loan_sub_category_id' => 16, 'sequence_no' => 9, 'name' => 'Attested photocopy of CNIC of applicant & Guarantors', 'status' => 'active'],
            ['loan_sub_category_id' => 16, 'sequence_no' => 10, 'name' => 'Photo Graphs of Business Place', 'status' => 'active'],
            ['loan_sub_category_id' => 16, 'sequence_no' => 11, 'name' => 'Photo Graphs of Business Place', 'status' => 'active'],
        ];

        foreach ($loan_sub_category as $lsc) {
            CheckList::create($lsc);
        }
    }
}
