<?php

namespace Database\Seeders;

use App\Models\Status;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class StatusSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //

        $statues = [
            ['name' => 'S/O', 'status' => 'Relationship', 'loan_sub_category_id' => NULL],
            ['name' => 'W/O', 'status' => 'Relationship', 'loan_sub_category_id' => NULL],
            ['name' => 'D/O', 'status' => 'Relationship', 'loan_sub_category_id' => NULL],
            ['name' => 'CEO', 'status' => 'Relationship', 'loan_sub_category_id' => NULL],
            ['name' => 'Director', 'status' => 'Relationship', 'loan_sub_category_id' => NULL],
            ['name' => 'Partner', 'status' => 'Relationship', 'loan_sub_category_id' => NULL],
            ['name' => 'Managing Partner', 'status' => 'Relationship', 'loan_sub_category_id' => NULL],
            ['name' => 'Male', 'status' => 'Gender', 'loan_sub_category_id' => NULL],
            ['name' => 'Female', 'status' => 'Gender', 'loan_sub_category_id' => NULL],
            ['name' => 'Company', 'status' => 'Gender', 'loan_sub_category_id' => NULL],
            ['name' => 'Government', 'status' => 'Employer Legal Status', 'loan_sub_category_id' => NULL],
            ['name' => 'Semi Government', 'status' => 'Employer Legal Status', 'loan_sub_category_id' => NULL],
            ['name' => 'Autonomous', 'status' => 'Employer Legal Status', 'loan_sub_category_id' => NULL],
            ['name' => 'Private', 'status' => 'Employer Legal Status', 'loan_sub_category_id' => NULL],
            ['name' => 'Others', 'status' => 'Employer Legal Status', 'loan_sub_category_id' => NULL],
            ['name' => 'Government', 'status' => 'Occupation Title', 'loan_sub_category_id' => NULL],
            ['name' => 'Semi Government', 'status' => 'Occupation Title', 'loan_sub_category_id' => NULL],
            ['name' => 'Autonomous Body', 'status' => 'Occupation Title', 'loan_sub_category_id' => NULL],
            ['name' => 'Business Men', 'status' => 'Occupation Title', 'loan_sub_category_id' => NULL],
            ['name' => 'Self Employed', 'status' => 'Occupation Title', 'loan_sub_category_id' => NULL],
            ['name' => 'Professional', 'status' => 'Occupation Title', 'loan_sub_category_id' => NULL],
            ['name' => 'Permanent', 'status' => 'Employment Status', 'loan_sub_category_id' => NULL],
            ['name' => 'Contractual (Private)', 'status' => 'Employment Status', 'loan_sub_category_id' => NULL],
            ['name' => 'On Deputation (Private)', 'status' => 'Employment Status', 'loan_sub_category_id' => NULL],
            ['name' => 'Regular', 'status' => 'Service Status', 'loan_sub_category_id' => NULL],
            ['name' => 'None', 'status' => 'Service Status', 'loan_sub_category_id' => NULL],
            ['name' => 'Single', 'status' => 'Marital Status', 'loan_sub_category_id' => NULL],
            ['name' => 'Married', 'status' => 'Marital Status', 'loan_sub_category_id' => NULL],
            ['name' => 'Widow', 'status' => 'Marital Status', 'loan_sub_category_id' => NULL],
            ['name' => 'Divorced', 'status' => 'Marital Status', 'loan_sub_category_id' => NULL],
            ['name' => 'None/Company', 'status' => 'Marital Status', 'loan_sub_category_id' => NULL],
            ['name' => 'Self Owned', 'status' => 'Home Status', 'loan_sub_category_id' => NULL],
            ['name' => 'Wife House', 'status' => 'Home Status', 'loan_sub_category_id' => NULL],
            ['name' => 'Husband House', 'status' => 'Home Status', 'loan_sub_category_id' => NULL],
            ['name' => 'Parent House', 'status' => 'Home Status', 'loan_sub_category_id' => NULL],
            ['name' => 'Rented', 'status' => 'Home Status', 'loan_sub_category_id' => NULL],
            ['name' => 'None/Company', 'status' => 'Home Status', 'loan_sub_category_id' => NULL],
            ['name' => 'Direct', 'status' => 'Salary Mode', 'loan_sub_category_id' => NULL],
            ['name' => 'Bank Transfer', 'status' => 'Salary Mode', 'loan_sub_category_id' => NULL],
            ['name' => 'Cash', 'status' => 'Salary Mode', 'loan_sub_category_id' => NULL],
            ['name' => 'Cheque', 'status' => 'Salary Mode', 'loan_sub_category_id' => NULL],
            ['name' => 'Via DDO', 'status' => 'Salary Mode', 'loan_sub_category_id' => NULL],
            ['name' => 'Consolidated cheque issued by DDO', 'status' => 'Salary Mode', 'loan_sub_category_id' => NULL],
            ['name' => 'Other', 'status' => 'Salary Mode', 'loan_sub_category_id' => NULL],
            ['name' => 'Fresh', 'status' => 'Status Request', 'loan_sub_category_id' => NULL],
            ['name' => 'Enhancement', 'status' => 'Status Request', 'loan_sub_category_id' => NULL],
            ['name' => 'Renewal', 'status' => 'Status Request', 'loan_sub_category_id' => NULL],
            ['name' => 'Reduction', 'status' => 'Status Request', 'loan_sub_category_id' => NULL],
            ['name' => 'Primary Security', 'status' => 'Security Type', 'loan_sub_category_id' => NULL],
            ['name' => 'Secondary Security', 'status' => 'Security Type', 'loan_sub_category_id' => NULL],
            ['name' => 'Industrial', 'status' => 'Business Nature', 'loan_sub_category_id' => NULL],
            ['name' => 'Commercial', 'status' => 'Business Nature', 'loan_sub_category_id' => NULL],
            ['name' => 'Agricultural', 'status' => 'Business Nature', 'loan_sub_category_id' => NULL],
            ['name' => 'Services', 'status' => 'Business Nature', 'loan_sub_category_id' => NULL],
            ['name' => 'Any Other', 'status' => 'Business Nature', 'loan_sub_category_id' => NULL],
            ['name' => '12 Months', 'status' => 'Loan Tenure', 'loan_sub_category_id' => NULL],
            ['name' => '24 Months', 'status' => 'Loan Tenure', 'loan_sub_category_id' => NULL],
            ['name' => '36 Months', 'status' => 'Loan Tenure', 'loan_sub_category_id' => NULL],
            ['name' => '48 Months', 'status' => 'Loan Tenure', 'loan_sub_category_id' => NULL],
            ['name' => '60 Months', 'status' => 'Loan Tenure', 'loan_sub_category_id' => NULL],
            ['name' => 'Pakistan', 'status' => 'Country', 'loan_sub_category_id' => NULL],
            ['name' => 'PKR', 'status' => 'Currency', 'loan_sub_category_id' => NULL],
            ['name' => 'Company', 'status' => 'Business Type', 'loan_sub_category_id' => NULL],
            ['name' => 'Sole Proprietorship', 'status' => 'Business Type', 'loan_sub_category_id' => NULL],
            ['name' => 'Partnership', 'status' => 'Business Type', 'loan_sub_category_id' => NULL],
            ['name' => 'Individual', 'status' => 'Business Type', 'loan_sub_category_id' => NULL],
            ['name' => 'CEO', 'status' => 'Business Designation', 'loan_sub_category_id' => NULL],
            ['name' => 'Director', 'status' => 'Business Designation', 'loan_sub_category_id' => NULL],
            ['name' => 'Managing Partner', 'status' => 'Business Designation', 'loan_sub_category_id' => NULL],
            ['name' => 'Partner', 'status' => 'Business Designation', 'loan_sub_category_id' => NULL],
            ['name' => 'New', 'status' => 'Vehicle Type', 'loan_sub_category_id' => NULL],
            ['name' => 'Used', 'status' => 'Vehicle Type', 'loan_sub_category_id' => NULL],
            ['name' => 'Individual', 'status' => 'Guarantor Type', 'loan_sub_category_id' => NULL],
            ['name' => 'Business', 'status' => 'Guarantor Type', 'loan_sub_category_id' => NULL],
            ['name' => 'Mr.', 'status' => 'Title', 'loan_sub_category_id' => NULL],
            ['name' => 'Ms.', 'status' => 'Title', 'loan_sub_category_id' => NULL],
            ['name' => 'Mrs.', 'status' => 'Title', 'loan_sub_category_id' => NULL],
            ['name' => 'Miss.', 'status' => 'Title', 'loan_sub_category_id' => NULL],
            ['name' => 'Loan', 'status' => 'Facility Type', 'loan_sub_category_id' => NULL],
            ['name' => 'Credit', 'status' => 'Facility Type', 'loan_sub_category_id' => NULL],
            ['name' => 'Mortgage', 'status' => 'Facility Type', 'loan_sub_category_id' => NULL],
            ['name' => 'Lease', 'status' => 'Facility Type', 'loan_sub_category_id' => NULL],
            ['name' => 'Other', 'status' => 'Facility Type', 'loan_sub_category_id' => NULL],
            ['name' => 'Active', 'status' => 'Finance Facility Status', 'loan_sub_category_id' => NULL],
            ['name' => 'Closed', 'status' => 'Finance Facility Status', 'loan_sub_category_id' => NULL],
            ['name' => 'Defaulted', 'status' => 'Finance Facility Status', 'loan_sub_category_id' => NULL],
            ['name' => 'Latest salary slip, stamped and signed by DDO ', 'status' => 'Document', 'loan_sub_category_id' => NULL],
            ['name' => 'Copy of CNIC Front Side', 'status' => 'Document', 'loan_sub_category_id' => NULL],
            ['name' => 'Copy of CNIC Back Side ', 'status' => 'Document', 'loan_sub_category_id' => NULL],
            ['name' => 'Guarantee Letter', 'status' => 'Document', 'loan_sub_category_id' => NULL],
            ['name' => 'Undertaking from DDO', 'status' => 'Document', 'loan_sub_category_id' => NULL],
            ['name' => 'Profile Picture', 'status' => 'Document', 'loan_sub_category_id' => NULL],
            ['name' => 'Yes', 'status' => 'Nadra Verification', 'loan_sub_category_id' => NULL],
            ['name' => 'No', 'status' => 'Nadra Verification', 'loan_sub_category_id' => NULL],
            ['name' => 'Secondary School Certificate / Matriculation / O - level', 'status' => 'Education Qualification', 'loan_sub_category_id' => NULL],
            ['name' => 'Higher Secondary School Certificate / Intermediate/ A - level', 'status' => 'Education Qualification', 'loan_sub_category_id' => NULL],
            ['name' => 'Bachelor (14 Years) Degree', 'status' => 'Education Qualification', 'loan_sub_category_id' => NULL],
            ['name' => 'Bachelor (16 Years) Degree', 'status' => 'Education Qualification', 'loan_sub_category_id' => NULL],
            ['name' => 'Master (16 Years) Degree', 'status' => 'Education Qualification', 'loan_sub_category_id' => NULL],
            ['name' => 'Master/ MS (18 Years) Degree', 'status' => 'Education Qualification', 'loan_sub_category_id' => NULL],
            ['name' => 'M-Phil (18 Years) Degree', 'status' => 'Education Qualification', 'loan_sub_category_id' => NULL],
            ['name' => 'Doctorate Degree', 'status' => 'Education Qualification', 'loan_sub_category_id' => NULL],
            ['name' => 'MS leading to PhD', 'status' => 'Education Qualification', 'loan_sub_category_id' => NULL],
            ['name' => 'Post Doctorate', 'status' => 'Education Qualification', 'loan_sub_category_id' => NULL],
            ['name' => 'PGD', 'status' => 'Education Qualification', 'loan_sub_category_id' => NULL],
            ['name' => 'None/Company', 'status' => 'Education Qualification', 'loan_sub_category_id' => NULL],
            ['name' => 'Monthly', 'status' => 'Repayment Frequency', 'loan_sub_category_id' => NULL],
            ['name' => 'Quarterly', 'status' => 'Repayment Frequency', 'loan_sub_category_id' => NULL],
            ['name' => 'Bi-Annually', 'status' => 'Repayment Frequency', 'loan_sub_category_id' => NULL],
            ['name' => 'Annually', 'status' => 'Repayment Frequency', 'loan_sub_category_id' => NULL],
            ['name' => 'Principal', 'status' => 'Repayment Frequency', 'loan_sub_category_id' => NULL],
            ['name' => 'Lumpsum', 'status' => 'Repayment Frequency', 'loan_sub_category_id' => NULL],
            ['name' => 'Markup Quarterly', 'status' => 'Repayment Frequency', 'loan_sub_category_id' => NULL],
            ['name' => 'New', 'status' => 'Vehicle Type', 'loan_sub_category_id' => NULL],
            ['name' => 'Used', 'status' => 'Vehicle Type', 'loan_sub_category_id' => NULL],

            // Advance Salary
            ['name' => 'Government', 'status' => 'occupation_title', 'loan_sub_category_id' => 1],
            ['name' => 'Semi Government', 'status' => 'occupation_title', 'loan_sub_category_id' => 1],
            ['name' => 'Autonomous', 'status' => 'occupation_title', 'loan_sub_category_id' => 1],
            ['name' => 'Individual', 'status' => 'borrower_type', 'loan_sub_category_id' => 1],
            ['name' => 'Male', 'status' => 'gender', 'loan_sub_category_id' => 1],
            ['name' => 'Female', 'status' => 'gender', 'loan_sub_category_id' => 1],
            ['name' => 'Single', 'status' => 'marital_status', 'loan_sub_category_id' => 1],
            ['name' => 'Married', 'status' => 'marital_status', 'loan_sub_category_id' => 1],
            ['name' => 'Widow', 'status' => 'marital_status', 'loan_sub_category_id' => 1],
            ['name' => 'Divorced', 'status' => 'marital_status', 'loan_sub_category_id' => 1],
            ['name' => 'S/O', 'status' => 'relationship_status', 'loan_sub_category_id' => 1],
            ['name' => 'W/O', 'status' => 'relationship_status', 'loan_sub_category_id' => 1],
            ['name' => 'D/O', 'status' => 'relationship_status', 'loan_sub_category_id' => 1],
            ['name' => 'SSC / Matriculation / O - level', 'status' => 'education_qualification', 'loan_sub_category_id' => 1],
            ['name' => 'HSSC / Intermediate / A - level', 'status' => 'education_qualification', 'loan_sub_category_id' => 1],
            ['name' => 'Bachelor (14 Years) Degree', 'status' => 'education_qualification', 'loan_sub_category_id' => 1],
            ['name' => 'Bachelor (16 Years) Degree', 'status' => 'education_qualification', 'loan_sub_category_id' => 1],
            ['name' => 'Master (16 Years) Degree', 'status' => 'education_qualification', 'loan_sub_category_id' => 1],
            ['name' => 'Master/ MS (18 Years) Degree', 'status' => 'education_qualification', 'loan_sub_category_id' => 1],
            ['name' => 'M-Phil (18 Years) Degree', 'status' => 'education_qualification', 'loan_sub_category_id' => 1],
            ['name' => 'Doctorate Degree', 'status' => 'education_qualification', 'loan_sub_category_id' => 1],
            ['name' => 'MS leading to PhD', 'status' => 'education_qualification', 'loan_sub_category_id' => 1],
            ['name' => 'Post Doctorate', 'status' => 'education_qualification', 'loan_sub_category_id' => 1],
            ['name' => 'PGD', 'status' => 'education_qualification', 'loan_sub_category_id' => 1],
            ['name' => 'Government', 'status' => 'employer_legal_status', 'loan_sub_category_id' => 1],
            ['name' => 'Semi Government', 'status' => 'employer_legal_status', 'loan_sub_category_id' => 1],
            ['name' => 'Autonomous', 'status' => 'employer_legal_status', 'loan_sub_category_id' => 1],
            ['name' => 'Others', 'status' => 'employer_legal_status', 'loan_sub_category_id' => 1],
            ['name' => 'Permanent', 'status' => 'employment_status', 'loan_sub_category_id' => 1],
            ['name' => 'Bank Transfer', 'status' => 'mode_of_salary_receipt', 'loan_sub_category_id' => 1],
            ['name' => 'Regular', 'status' => 'repayment_status', 'loan_sub_category_id' => 1],
            ['name' => 'Irregular', 'status' => 'repayment_status', 'loan_sub_category_id' => 1],
            ['name' => 'NPL', 'status' => 'repayment_status', 'loan_sub_category_id' => 1],
            ['name' => 'Fund Based', 'status' => 'facility_type', 'loan_sub_category_id' => 1],
            ['name' => 'Non Fund Based', 'status' => 'facility_type', 'loan_sub_category_id' => 1],
            ['name' => 'Fresh', 'status' => 'status', 'loan_sub_category_id' => 1],
            ['name' => 'Enhancement', 'status' => 'status', 'loan_sub_category_id' => 1],
            ['name' => 'Renewal', 'status' => 'status', 'loan_sub_category_id' => 1],
            ['name' => 'Reduction', 'status' => 'status', 'loan_sub_category_id' => 1],
            ['name' => 'Monthly', 'status' => 'repayment_frequency', 'loan_sub_category_id' => 1],
            ['name' => 'Quarterly', 'status' => 'repayment_frequency', 'loan_sub_category_id' => 1],
            ['name' => 'Bi-Annually', 'status' => 'repayment_frequency', 'loan_sub_category_id' => 1],
            ['name' => 'Annually', 'status' => 'repayment_frequency', 'loan_sub_category_id' => 1],
            ['name' => 'Principal', 'status' => 'repayment_frequency', 'loan_sub_category_id' => 1],
            ['name' => 'Lumpsum', 'status' => 'repayment_frequency', 'loan_sub_category_id' => 1],
            ['name' => 'Markup Quarterly', 'status' => 'repayment_frequency', 'loan_sub_category_id' => 1],
            ['name' => 'Yes', 'status' => 'is_insured', 'loan_sub_category_id' => 1],
            ['name' => 'KIBOR', 'status' => 'markup_rate_type', 'loan_sub_category_id' => 1],
            ['name' => 'FIXED', 'status' => 'markup_rate_type', 'loan_sub_category_id' => 1],
            ['name' => 'Fund Based', 'status' => 'fund_based_non_fund_based', 'loan_sub_category_id' => 1],
            ['name' => 'Hypothecation of House Hold Item', 'status' => 'security_type', 'loan_sub_category_id' => 1],
            ['name' => 'Personal Guarantee', 'status' => 'security_type', 'loan_sub_category_id' => 1],
            ['name' => 'Post Dated Cheques', 'status' => 'security_type', 'loan_sub_category_id' => 1],
            ['name' => 'Yes', 'status' => 'cheques_obtained', 'loan_sub_category_id' => 1],
            ['name' => 'No', 'status' => 'cheques_obtained', 'loan_sub_category_id' => 1],





        ];


        foreach ($statues as $status) {
            Status::create($status);
        }
    }
}
